# Generated by Django 6.0.4 on 2026-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('good', 'Good'), ('ripe', 'Ripe')], default='fresh', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
