# Generated by Django 6.0.4 on 2026-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_order_status_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
